### ISSUE TITLE
jbig2dec Fatal error Not a jbig2 file header

### ISSUE THREAD

**Issue by vishwas1384** [rillian/jbig2dec#1]
Hi,

I am new to image decoding and came across jbig2dec for decoding jbig2 files. 

I encoded the Winter.jpg to Winter.jbig2 file using the command in Windows XP cmd:

jbig2 -s -v Winter.jpg > Winter.jbig2

I got the file Winter.jbig2.

Now when I decode the file using the command

jbig2dec -o Winter Winter.jbig2

an error is displayed
jbig2dec Fatal error Not a jbig2 file header.

Attaching the files for your reference. Can you please let me know where am I going wrong. 

Hoping to get your help,hints at the earliest.

Thanks & Regards

![winter](https://cloud.githubusercontent.com/assets/10235391/5509319/b57952c0-87dc-11e4-9090-25396b8159ff.jpg)

**Comment by rillian** [comment]
Works for me. Maybe your jbig2 encoder invocation failed and Winter.jbig2 contains an error message instead of an image?
![winter](https://cloud.githubusercontent.com/assets/225102/5512326/f39685d0-878e-11e4-9227-29c597d1d3f8.png)

**Comment by vishwas1384** [comment]
Got the solution to the problem. 
The encoder fails to invoke the file.

Thanks for the reply.

**Comment by vishwas1384** [comment]
Can the decoder decode the images to user specified format?
If so can you tell me briefly how to do it?
 Searching for a way to decode the jbig2 files into tiff or jpeg file format.

**Comment by rillian** [comment]
jbig2dec has optional png output support. Try `jbig2dec -o winter.png winter.jbig2`. By default, or if it was compiled without png support, it will create a pbm file. You can convert this to jpeg or tiff with a program like ImageMagick.

```
jbig2dec winter.jbig2
convert winter.pbm winter.tiff
```

**Comment by vishwas1384** [comment]
Can you give a link to the compiled version of jbig2dec that has optional support for a png file? The version that I have only supports pbm file format.

Regards

**Comment by rillian** [comment]
I can try. What operating system do you want support for?

**Comment by vishwas1384** [comment]
Windows 7 64 bit operating system. If possible can the decoder decode the jbig2 file to jpeg file without increasing the file size?

Regards

**Comment by rillian** [comment]
A jpeg is generally going to be bigger than the corresponding jbig2 file. Otherwise we wouldn't have needed jbig2!

JBIG is designed for black & white scanned documents though, which have very different characteristics than the natural photos jpeg was designed for. So they're optimum for different types of images.

**Comment by vishwas1384** [comment]
Hi Ralph,

Thank you for your response to my queries. I got the JPedal library to
view/ convert the files to png format and satisfied with the results.
Wishing you merry Christmas and a happy new year.

Regards,
Vishwas
